nil check failed
0: f(Foo): 10
1: main(): 6
