//= "caught\nafter\nend\n"

fun main() {
  do {
    throwFromNative(true);
    assert(false);
  } catch e: Exception {
    println("caught");
    assert(true);
  }

  println("after");
  throwFromNative(false);
  println("end");
}
