//= error exception

fun main() {
  throw "error";
}
